(()=>{
const VERSION='jolly-private-awakening-retry-2.1',DELAY=350;
const clean=s=>String(s||'').replace(/\s+/g,' ').trim(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const abs=(u,b=location.href)=>{try{return new URL(u||'',b).href}catch(e){return u||''}};
let old=document.getElementById('jolly-awakening-retry-v2');if(old)old.remove();
const panel=document.createElement('div');panel.id='jolly-awakening-retry-v2';panel.style='position:fixed;z-index:2147483647;left:6px;right:6px;top:6px;background:#111;color:#fff;padding:10px;border-radius:10px;font-size:13px;line-height:1.35;max-height:64vh;overflow:auto;font-family:-apple-system,sans-serif;box-shadow:0 2px 14px #000a';
panel.innerHTML='<b>JOLLY 覚醒のみ再取得 v2</b> <span id="jar-st">起動中</span><div style="height:7px;background:#444;margin:7px 0"><div id="jar-bar" style="height:7px;width:2%;background:#ddd"></div></div><div id="jar-sum">固定パネルを準備しました</div><pre id="jar-log" style="white-space:pre-wrap;background:#222;padding:6px;max-height:24vh;overflow:auto"></pre><div id="jar-btn"></div>';
(document.body||document.documentElement).appendChild(panel);
const $=x=>document.getElementById(x),st=$('jar-st'),bar=$('jar-bar'),sum=$('jar-sum'),logEl=$('jar-log'),btn=$('jar-btn');
const state={steps:[],warnings:[],errors:[],result:null};
function log(s,k='INFO'){const x='['+new Date().toLocaleTimeString()+'] '+k+' '+s;state.steps.push(x);logEl.textContent+=(logEl.textContent?'\n':'')+x;logEl.scrollTop=logEl.scrollHeight}
function fail(e,w){state.errors.push({where:w,message:String(e?.message||e)});log(w+': '+String(e?.message||e),'ERROR')}
function progress(n,s){bar.style.width=Math.max(2,Math.min(100,n))+'%';st.textContent=s}
function addButton(t,f){const b=document.createElement('button');b.textContent=t;b.style='padding:9px;margin:8px 7px 0 0';b.onclick=f;btn.appendChild(b)}
function save(obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download='jolly_private_awakening_retry_v2.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}
function buttons(){btn.innerHTML='';addButton('JSON保存',()=>save(state.result||state));addButton('JSONコピー',async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state.result||state,null,2));alert('コピーしました')}catch(e){fail(e,'copy')}});addButton('終了',()=>{panel.remove();try{completion({ok:Boolean(state.result?.meta?.audit_ok),version:VERSION})}catch(e){}})}
buttons();
function docOf(html){return new DOMParser().parseFromString(html,'text/html')}
async function get(url){const r=await fetch(url,{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status+' '+url);return {doc:docOf(await r.text()),url:r.url||url}}
function pageCount(doc){let max=0;for(const a of doc.querySelectorAll('a[href*="p="]'))try{max=Math.max(max,Number(new URL(a.href,location.href).searchParams.get('p'))||0)}catch(e){}return max+1}
function blockOf(node){return node.closest('li')||node.closest('[class*="card_list"]')||node.parentElement?.parentElement||node.parentElement}
function parseCards(doc,base){const out=[],seen=new Set();for(const a of doc.querySelectorAll('a[href*="M=Composition"][href*="A=Check"][href*="base="]')){const u=new URL(a.getAttribute('href'),base),id=u.searchParams.get('base')||'';if(!id||seen.has(id))continue;seen.add(id);const block=blockOf(a),text=clean(block?.textContent),img=block?.querySelector('img[src*="/img/card/"]'),im=(img?.getAttribute('src')||'').match(/\/card\/(?:120|320)\/([0-9]+)/),lv=text.match(/Lv\.?\s*([0-9]+)\s*\/\s*([0-9]+)/),aw=text.match(/覚醒(?:回数)?\s*[：:]?\s*([0-9]+)(?:\s*\/\s*([0-9]+))?/);out.push({base_instance_id:id,card_image_id:im?im[1]:'',card_name:clean(block?.querySelector('.cardcolor_name')?.textContent)||clean(text.split(/\[|Lv\./)[0]),level:lv?Number(lv[1]):null,level_max:lv?Number(lv[2]):null,awakening_count:aw?Number(aw[1]):null,awakening_max_site:aw&&aw[2]?Number(aw[2]):null,remaining_awakenings_site:aw&&aw[2]?Number(aw[2])-Number(aw[1]):null,check_url:u.href})}return out}
function parseMaterials(doc){const out=[];for(const el of doc.querySelectorAll('li,div')){const t=clean(el.textContent),m=t.match(/((?:キング)?(?:転生)?らいおん|(?:伝説|究極|至高|上級|中級|下級)?とくぱん|[0-9]+周年[^\s]*)[^0-9]{0,12}([0-9,]+)\s*(?:個|枚)/);if(m&&!out.some(x=>x.material_name===m[1]))out.push({material_name:m[1],owned_count_site:Number(m[2].replace(/,/g,''))})}return out}
(async()=>{try{const base=abs('?M=Composition&A=Default&sort=17&property=0&card_cost=0&card_skill=0&card_name=0&card_rare=0'),first=await get(base),pages=pageCount(first.doc),cards=[],status=[];let materials=[];if(pages<2)throw Error('覚醒一覧のページ数を確認できません: '+pages);for(let i=0;i<pages;i++){try{const r=i?await get(base+'&p='+i):first,part=parseCards(r.doc,r.url);cards.push(...part);materials=materials.concat(parseMaterials(r.doc));status.push({page_index:i,ok:true,row_count:part.length});progress(Math.round((i+1)/pages*95),'覚醒 '+(i+1)+'/'+pages);log('覚醒 '+(i+1)+'/'+pages+' '+part.length+'件')}catch(e){status.push({page_index:i,ok:false,row_count:0,error:String(e)});fail(e,'page '+i)}await sleep(DELAY)}const unique=[...new Map(cards.map(x=>[x.base_instance_id,x])).values()],mats=[...new Map(materials.map(x=>[x.material_name,x])).values()],ok=status.every(x=>x.ok)&&unique.length>0&&mats.length>0;state.result={version:VERSION,collected_at:new Date().toISOString(),privacy:'private_do_not_publish_to_github_pages',meta:{pages_expected:pages,pages_ok:status.filter(x=>x.ok).length,awakening_card_count:unique.length,material_type_count:mats.length,audit_ok:ok},awakening_cards:unique,awakening_materials:mats,page_status:status,errors:state.errors,steps:state.steps};sum.innerHTML='<b>取得完了</b><br>覚醒対象 '+unique.length+' / 素材 '+mats.length+'種類<br>監査 '+(ok?'OK':'REVIEW_REQUIRED')+'<br><b>JSONを保存してください。</b>';progress(100,ok?'完了':'要確認');buttons()}catch(e){fail(e,'main');state.result={version:VERSION,collected_at:new Date().toISOString(),privacy:'private_do_not_publish_to_github_pages',meta:{audit_ok:false},errors:state.errors,steps:state.steps};sum.textContent='停止: '+String(e?.message||e);progress(100,'エラー');buttons()}})();
})();
